/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-WSPR_Encoder
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_WSPR_ENCODER_API_H
#define INCLUDED_WSPR_ENCODER_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_WSPR_Encoder_EXPORTS
#define WSPR_ENCODER_API __GR_ATTR_EXPORT
#else
#define WSPR_ENCODER_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_WSPR_ENCODER_API_H */
