find_package(PkgConfig)

PKG_CHECK_MODULES(PC_GR_PASSTHROUGH_DIGITALRF_WRITER gnuradio-Passthrough_DigitalRF_Writer)

FIND_PATH(
    GR_PASSTHROUGH_DIGITALRF_WRITER_INCLUDE_DIRS
    NAMES gnuradio/Passthrough_DigitalRF_Writer/api.h
    HINTS $ENV{PASSTHROUGH_DIGITALRF_WRITER_DIR}/include
        ${PC_PASSTHROUGH_DIGITALRF_WRITER_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    GR_PASSTHROUGH_DIGITALRF_WRITER_LIBRARIES
    NAMES gnuradio-Passthrough_DigitalRF_Writer
    HINTS $ENV{PASSTHROUGH_DIGITALRF_WRITER_DIR}/lib
        ${PC_PASSTHROUGH_DIGITALRF_WRITER_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
          )

include("${CMAKE_CURRENT_LIST_DIR}/gnuradio-Passthrough_DigitalRF_WriterTarget.cmake")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GR_PASSTHROUGH_DIGITALRF_WRITER DEFAULT_MSG GR_PASSTHROUGH_DIGITALRF_WRITER_LIBRARIES GR_PASSTHROUGH_DIGITALRF_WRITER_INCLUDE_DIRS)
MARK_AS_ADVANCED(GR_PASSTHROUGH_DIGITALRF_WRITER_LIBRARIES GR_PASSTHROUGH_DIGITALRF_WRITER_INCLUDE_DIRS)
