/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-Passthrough_DigitalRF_Writer
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_PASSTHROUGH_DIGITALRF_WRITER_API_H
#define INCLUDED_PASSTHROUGH_DIGITALRF_WRITER_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_Passthrough_DigitalRF_Writer_EXPORTS
#define PASSTHROUGH_DIGITALRF_WRITER_API __GR_ATTR_EXPORT
#else
#define PASSTHROUGH_DIGITALRF_WRITER_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_PASSTHROUGH_DIGITALRF_WRITER_API_H */
